import { caller, getQueryClient, trpc } from "@/trpc/server";
import { AppSidebar } from "./_components/(store-admin-dashboard)/app-sidebar";
import { SiteHeader } from "./_components/(store-admin-dashboard)/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { Suspense } from "react";
import { Navbar } from "@/app/(main)/_components/navbar";
import { Metadata } from "next";

interface LayoutProps {
  params: Promise<{
    storeName: string;
  }>;
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function StoreNameLayout({
  children,
  params,
}: LayoutProps) {
  const { storeName } = await params;

  const isAdmin = await caller.stores.checkIsAdmin({
    storeName,
  });

  console.log(isAdmin);

  if (!isAdmin) {
    return (
      <div>
        <Navbar />
      </div>
    );
  }

  const queryClient = getQueryClient();

  void queryClient.prefetchQuery(
    trpc.carts.getCartByStoreName.queryOptions({
      storeName,
    })
  );

  return (
    <SidebarProvider>
      <AppSidebar variant="inset" />
      <SidebarInset>
        <HydrationBoundary state={dehydrate(queryClient)}>
          <Suspense>
            <SiteHeader storeName={storeName} />
          </Suspense>
        </HydrationBoundary>
        <div className="p-6">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  );
}
